ALTER TABLE CHIEN DROP CONSTRAINT FK_CHIEN_ID_CHENIL
ALTER TABLE PERSONNE DROP CONSTRAINT FK_PERSONNE_ID_CHIEN
ALTER TABLE PATHOLOGIE DROP CONSTRAINT FK_PATHOLOGIE_ID_CHIEN
DROP TABLE CHIEN
DROP TABLE PERSONNE
DROP TABLE CHENIL
DROP TABLE PATHOLOGIE
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
